### ISSUE TITLE
Double-click the node title to edit

### ISSUE THREAD

**Issue by za-wa-n-go** [coolzilj/ComfyUI-LJNodes#1]
When changing parameters such as the number of steps, it frequently malfunctions. I would appreciate it if you could limit the double-click area to the top of the node or, if that's difficult, make it possible to turn off this feature. 

The shortcut for group nodes is extremely convenient!

**Comment by coolzilj** [comment]
> When changing parameters such as the number of steps, it frequently malfunctions. I would appreciate it if you could limit the double-click area to the top of the node or, if that's difficult, make it possible to turn off this feature.
> 
> The shortcut for group nodes is extremely convenient!

It's fixed 15 hours ago, try update to the lastest.

**Comment by za-wa-n-go** [comment]
Thakyou!
