### ISSUE TITLE
Can not find it in Comfy Manager

### ISSUE THREAD

**Issue by nodegraphics** [coolzilj/ComfyUI-LJNodes#2]
Hello,
It doesn't appear via Comfy manager, I couldn't find it....and wanted to ask before `git clone`

**Comment by coolzilj** [comment]
it will show up after https://github.com/ltdrdata/ComfyUI-Manager/pull/757 is merged.
Before that just git clone.

**Comment by nodegraphics** [comment]
got it. Thank you
