### ISSUE TITLE
Padding for ctrl+g group.

### ISSUE THREAD

**Issue by moon47usaco** [coolzilj/ComfyUI-LJNodes#9]
Can you add a setting to set desired amount of padding around the nodes instead of exact fit.

What a wonderful node pack by the way, thank you... =]

**Comment by coolzilj** [comment]
OCD delights, I love this idea. Will do it.

**Comment by coolzilj** [comment]
Added, but it only works with the shortcut (Ctrl+G). 
It doesn't affect the default padding when you use the action from the right-click menu. This is a bit tricky because I can't change it in a custom node; I'd need to modify the source code in ComfyUI.

**Comment by moon47usaco** [comment]
Excellent... Did not even know there was a rt-click menu.

I will update and check it out shortly...

Thank you... =]
